name: New PST Issuer
description: Registration for a new Private State Token Issuer.
title: "Private State Token Issuer Request - {Issuer Name}"
labels: ["pst-issuer"]
assignees:
 - dvorak42
body:
body:
  - type: markdown
    attributes:
      value: |
        Registration as a Private State Token Issuer.
  - type: input
    id: name
    attributes:
      label: Issuer Name
      description: Human-readable name representing the issuer website.
      placeholder: issuer.example Issuer
    validations:
      required: true
  - type: input
    id: origin
    attributes:
      label: Origin
      description: The [origin](https://developer.mozilla.org/en-US/docs/Glossary/Origin) that is used for the issuing service (scheme, host, port). The scheme must be HTTPS.
      placeholder: https://issuer.example
    validations:
      required: true
  - type: input
    id: contact
    attributes:
      label: Contact Email
      description: An email or email alias that is monitored by the issuer’s operator for issues regarding the issuer website.
      placeholder: admin@issuer.example
    validations:
      required: true
  - type: input
    id: key-commitments
    attributes:
      label: Key Commitment Endpoint URL
      description: A public HTTPS endpoint that responds to key commitment requests as described in the [specification](https://wicg.github.io/trust-token-api/#issuer-public-keys).
      placeholder: https://issuer.example/pst/keys
    validations:
      required: true
  - type: textarea
    id: purpose
    attributes:
      label: Purpose
      description: A description of the issuer, describing the intended purpose of the tokens.
      placeholder: To detect fraud using trust signals.
    validations:
      required: true
  - type: checkboxes
    id: disclosure
    attributes:
      label: |
        Disclosure & Acknowledgement
        1. I understand the technical restrictions on key rotation frequency of 60 days in the PST API.
        2. I understand that my issuer registration will be valid for a period of six months after the key commitment is accepted, and that I will need to re-register in this repository following that six-month period.
        3. I understand that in the future renewing my registration for this API may have additional requirements, to reduce the risk of abuse by token issuers.
      options:
        - label: I agree to this Disclosure and Acknowledgement
          required: true